/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const commonCategoryProps = {
  collapsed: false,
  type: 'category',
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
/** @docs https://docusaurus.io/docs/sidebar **/
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  docs: [
    'introduction',
    {
      ...commonCategoryProps,
      label: 'Code Style',
      items: [{ type: 'autogenerated', dirName: 'code-style' }],
    },
    {
      ...commonCategoryProps,
      label: 'Product Guide',
      items: [
        {
          ...commonCategoryProps,
          label: '2022 & Beyond',
          collapsed: true,
          items: [{
            type: 'autogenerated',
            dirName: 'product-guide/2022-and-beyond',
          }],
        },
        {
          ...commonCategoryProps,
          label: 'Before 2022',
          collapsed: true,
          items: [{
            type: 'autogenerated',
            dirName: 'product-guide/before-2022',
          }],
        },
      ],
    },
  ],
}

module.exports = sidebars
